### ISSUE TITLE
"Cannot read property 'replace' of undefined" with multiple nested routes

### ISSUE THREAD

**Issue by nickdaugherty** [AlbertoFdzM/express-list-endpoints#17]
When attempting to print the routes of a router that has multiple nested routes of arbitrary depth, I get the following (on Express 4.14.x):

```
TypeError: Cannot read property 'replace' of undefined
      at /usr/src/app/node_modules/express-list-endpoints/index.js:40:34
      at Array.forEach (native)
      at getEndpoints (/usr/src/app/node_modules/express-list-endpoints/index.js:26:9)
      at /usr/src/app/node_modules/express-list-endpoints/index.js:49:9
      at Array.forEach (native)
      at getEndpoints (/usr/src/app/node_modules/express-list-endpoints/index.js:26:9)
...
```

I believe there is something up with the regex and how it interacts with multi-level nested routes. For reference, my router looks something like this:

```
const router = express.Router();

router.use( '/top-level-route', require( './sub-route' ) );
```

**sub-route.js**
```
const router = require( 'express' ).Router({ mergeParams: true });

router.use( '/:id/sub-sub-route', require( './sub-sub-route' ) );

router.route( '/' ).post( function( req, res, next ) {

});

module.exports = router;
```

**Comment by AlbertoFdzM** [comment]
Thanks for the heads up!

Will Implement some test similar to that router config.

Not sure if it's for the `mergeParams: true` or the `'/:id/sub-sub-route'`.

**Comment by nickdaugherty** [comment]
Fix looks good and works for me, thank you!
